---
- hosts: common
  remote_user: root
  roles:
  - common

- hosts: web
  remote_user: root
  roles:
  - nginx

- hosts: tomcat
  remote_user: root
  roles:
  - tomcat

- hosts: backup_server
  remote_user: root
  roles:
  - backup_server
