---
- hosts: common
  remote_user: root
  roles:
  - common

- hosts: docker
  remote_user: root
  roles:
  - docker
  
- hosts: web
  remote_user: root
  roles:
  - nginx

- hosts: tomcat
  remote_user: root
  roles:
  - tomcat
