---
   - name: Install Nginx
     yum: name=nginx state=present

   - name: Start Nginx
     service: name=nginx state=started enabled=yes

   - name: Copy nginx.conf
     template: src=nginx.conf.v1 dest=/etc/nginx/nginx.conf
     notify: restart nginx
